### ISSUE TITLE
ARI scan resulting in module_defaults being copied to each of the tasks which is unexpected

### ISSUE THREAD

**Issue by justjais** [ansible/ansible-risk-insight#222]
ARI scan resulting in module_defaults being copied to each of the tasks which is unexpected. Please ref the example below:

Input play:
========
```
- name: rds_instance / processor integration tests
  collections:
  - community.aws
  module_defaults:
	group/aws:
  	aws_access_key: '{{ aws_access_key }}'
  	aws_secret_key: '{{ aws_secret_key }}'
  	security_token: '{{ security_token | default(omit) }}'
  	region: '{{ aws_region }}'
  block:
  - name: Ensure the resource doesn't exist
	rds_instance:
  	id: '{{ instance_id }}'
  	state: absent
  	skip_final_snapshot: true
	register: result
```

Output play:
=========
```
- name: Ensure the resource doesn't exist
  register: result
  amazon.aws.rds_instance:
	id: "{{ instance_id }}"
	state: "absent"
	skip_final_snapshot: true
  module_defaults:
	group/aws:
  	aws_access_key: '{{ aws_access_key }}'
  	aws_secret_key: '{{ aws_secret_key }}'
  	security_token: '{{ security_token | default(omit) }}'
  	region: '{{ aws_region }}'

- ansible.builtin.assert:
	that:
	- not result.changed
  module_defaults:
	group/aws:
  	aws_access_key: '{{ aws_access_key }}'
  	aws_secret_key: '{{ aws_secret_key }}'
  	security_token: '{{ security_token | default(omit) }}'
  	region: '{{ aws_region }}'
```

The following issue is observed in the repo: [LoadBotTesting-3](https://github.com/justjais/LoadBotTesting-3) from the task file of [rds_instance_processor](https://github.com/justjais/LoadBotTesting-3/blob/main/tests/integration/targets/rds_instance_processor/tasks/main.yml), but the issue is relevant for other repos play as well
