### ISSUE TITLE
ARI scanning is resulting in to truncated output

### ISSUE THREAD

**Issue by justjais** [ansible/ansible-risk-insight#223]
ARI scanning is resulting in to truncated output. The following issue is observed in the repo: [LoadBotTesting-2](https://github.com/justjais/LoadBotTesting-2). Please ref the below play:

Input Play:
========
```
---
  - name: Define timestamp
	set_fact: timestamp="{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
	run_once: true
  - name: Define file to place results
	set_fact: template={{rootdir}}/{{host}}/{{host}}_{{datatype}}_{{timestamp}}
  - name: Create dropoff directory for host
	file:
  	path: "{{ rootdir }}/{{ host }}"
  	state: directory
```

Output Play:
=========
```
- name: Define timestamp
  run_once: true
  ansible.builtin.set_fact:
	timestamp: "\"{{"

- name: Define file to place results
  ansible.builtin.set_fact:
	template: "{{rootdir}}/{{host}}/{{host}}_{{datatype}}_{{timestamp}}"

- name: Create dropoff directory for host
  ansible.builtin.file:
	path: "{{ _path_ }}"
	state: "directory"
```
