### ISSUE TITLE
ARI inline replace functionaity is overwritting the comment line

### ISSUE THREAD

**Issue by justjais** [ansible/ansible-risk-insight#247]
I've found one bug with ARI inline replace fix, ref:
`Input play:`
```
- tags:
    - freeipa_server
  block:

    - name: Check that the hostname has two-levels
      ansible.builtin.assert:
        that: ansible_facts["nodename"].split(".") | length >= 3
@@ -26,7 +25,6 @@
        ipaserver_realm: "{{ freeipa_server__realm }}"
        ipaserver_setup_firewalld: false

    # we need to use shell instead of command for the kerberos ticket to work
    - name: Kinit
      ansible.builtin.shell: echo '{{ freeipa_server__ipa_admin_password }}' | kinit
```
`Output play:`
```
- tags:
    - freeipa_server
  block:
    - name: Check that the hostname has two-levels
      ansible.builtin.assert:
        that: ansible_facts["nodename"].split(".") | length >= 3
@@ -26,7 +25,6 @@
        ipaserver_realm: "{{ freeipa_server__realm }}"
        ipaserver_setup_firewalld: false

    - name: Kinit
      ansible.builtin.shell: echo '{{ freeipa_server__ipa_admin_password }}' | kinit
```
`# we need to use shell instead of command for the kerberos ticket to work`, comment line is not being copied to Output play which isn't expected.
Playbook where issue is observed, [ref](https://github.com/justjais/LoadBotTesting-1/blob/main/roles/freeipa_server/tasks/main.yml#L29)
