### ISSUE TITLE
Line number detection bug when some types of specific blocks are present

### ISSUE THREAD

**Issue by hirokuni-kitahara** [ansible/ansible-risk-insight#251]
- When there is a `handlers` block under tasks, the line containing `handlers:` will be detected not as handler but as the last task.
- When `...` is included in the YAML, this line will be detected as the last task.

```yaml
---
- name: Copy Apache configuration file over and restart httpd
  hosts: all
  tasks:
    - name: Copy Apache configuration file over
      copy:
        src: /etc/httpd/conf/httpd.conf
        dest: /etc/httpd/conf/httpd.conf.bak
        remote_src: true
        owner: root
        group: root
        mode: "0644"
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
      notify: Restart httpd
  handlers:
    - name: Restart httpd
      service:
        name: httpd
        state: restarted
...
```
