### ISSUE TITLE
Line number detection bug when identical tasks are present in a single YAML

### ISSUE THREAD

**Issue by hirokuni-kitahara** [ansible/ansible-risk-insight#252]
- When there are some identical tasks in a single YAML, line numbers of them are all detected as the one of the first task

```yaml
---
- name: Test play 1
  hosts: localhost
  tasks:
    - name: Create checkpoint host 192.168.0.40
      checkpoint_host:
        name: checkpoint_host_1
        ip_address: 192.168.0.40
        state: present
- name: Test play 2
  hosts: localhost
  tasks:
    # the value of `line_numbers` attr of this task will be the one of the first task
    - name: Create checkpoint host 192.168.0.40
      checkpoint_host:
        name: checkpoint_host_1
        ip_address: 192.168.0.40
        state: present
```
