### ISSUE TITLE
ARI release 0.2.8 inline replace functionality is not performing as expected

### ISSUE THREAD

**Issue by justjais** [ansible/ansible-risk-insight#257]
ARI release `0.2.8` inline replace functionality is not performing as expected, ref below scenario:
Input:
```
---
- name: Parse bgp summary
  ansible.utils.cli_parse:
    command: "show ip bgp summary"
    parser:
      name: ansible.netcommon.content_templates
    set_fact: bgp_health
```
Output:
```
- name: Parse bgp summary
  ansible.utils.cli_parse:
    command: show ip bgp summary
    parser:
      name: ansible.netcommon.content_templates
```
In above output `---` yaml is missing, and also `set_fact: bgp_health` is not being replaced as expected after inline replace

Input:
```
---
- name: Parse bgp summary
  ansible.utils.cli_parse:
    command: "show bgp summary"
    parser:
      name: ansible.netcommon.content_templates
    set_fact: bgp_health


- name: Show Summary facts
  debug:
    msg: "{{ bgp_health }}"
```
Output:
```

- name: Parse bgp summary
  ansible.utils.cli_parse:
    command: show bgp summary
    parser:
      name: ansible.netcommon.content_templates
    set_fact: bgp_health
- name: Show Summary facts
  ansible.builtin.debug:
```
As, in above output `---` yaml syntax is replaced and debug `msg` is not being replaced as expected post inline replace functionality
